class Failure {
  final Exception e;

  const Failure(this.e);
}
